version: '2'

run:
  timeout: 15m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  default: none

  enable: # please keep this alphabetized
  - gocritic
  - gocyclo
  - govet
  - ineffassign
  - misspell
  - prealloc
  - promlinter
  - revive
  - staticcheck
  - unconvert
  - unparam
  - unused

  exclusions:
    generated: lax

    presets:
    - comments

    rules:
    - linters: ['revive']
      text: '^blank-imports:'

    - linters: ['revive']
      text: '^redefines-builtin-id:'

formatters:
  enable: # please keep this alphabetized
  - gofmt
  - gofumpt
  - goimports
